fitur_3/urls.py
from django.conf.urls import url
from .views import index
#url formar app
urlpatterns = [
    url(r'^$', index, name='index'),
]

fitur_add_friend/urls.py
from django.conf.urls import url
from .views import index
from .views import add_friend_post
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend/$', add_friend_post, name='add_friend'),
]

fitur_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

tugas_1/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status
from django.conf.urls import url, include
import fitur_profile.urls as fitur_profile

#url formar app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status', delete_status, name='delete_status'),
    url(r'^#t1/', include(fitur_profile,namespace='fitur-profile')),


]

tugas_ppw_1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import tugas_1.urls as tugas_1
import fitur_3.urls as fitur_3
import fitur_profile.urls as profile
import fitur_add_friend.urls as add_friend


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include(tugas_1,namespace='tugas-1')),
    url(r'^statistics/', include(fitur_3,namespace='fitur-3')),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^friends/', include(add_friend, namespace='friends')),
    url(r'^$', RedirectView.as_view(url='/status/', permanent=True), name = 'index'),

]

fitur_3/models.py
from django.db import models

# Create your models here.

fitur_add_friend/models.py
from django.db import models
import datetime

class Friend(models.Model):
    name = models.CharField(max_length=30)
    url = models.URLField(max_length=128)
    created_date = models.DateTimeField(auto_now_add=True)

fitur_profile/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	birth_date = models.DateField()
	gender = models.CharField(max_length=10)
	email = models.EmailField(max_length=70)
	description = models.TextField(max_length=20000)
	photo = models.URLField()

class Expertise(models.Model):
	expertise = models.CharField(max_length=20)
	person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='expertises')

tugas_1/models.py
from django.db import models

class Status(models.Model):
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

fitur_add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan url',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=True, max_length=30, widget=forms.TextInput(attrs=attrs))
    url = forms.URLField(required=True, widget=forms.URLInput(attrs=attrs))

tugas_1/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs = {
        'type': 'text',
        'cols': 100,
        'rows': 10,
        'class': 'status-form-textarea',
        'placeholder':'Apa Kabar Anda Hari Ini?',
        'max_length' : 140,
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

fitur_3/views.py
from django.shortcuts import render
from datetime import datetime, date
from fitur_profile.models import Person
from fitur_add_friend.models import Friend
from tugas_1.models import Status

# Enter your name here
# Create your views here.
def index(request):
    profile = Person.objects.get(pk=1)
    response = {'profile': profile,'friends':len(Friend.objects.all()),'feeds':len(Status.objects.all()),}
    response['latest'] = Status.objects.last()
    return render(request, 'contact.html', response)

fitur_add_friend/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import Add_Friend_Form
from .models import Friend

response = {}

def index(request):
    response['add_friend_form'] = Add_Friend_Form
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'friends.html'
    return render(request, html, response)

def add_friend_post(request):
    form = Add_Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        new_friend = Friend(name=response['name'], url=response['url'])
        new_friend.save()
    return HttpResponseRedirect('/friends/')

fitur_profile/views.py
from django.shortcuts import render
from fitur_profile.models import Expertise, Person
from .models import Person

# Create your views here.
def index(request):
	# expertises = Expertise.objects.all()
	# person = Person.objects.first()
	# response = {"person": person, "expertises": expertises}
	profile = Person.objects.first()
	expertises = profile.expertises.all()
	response = {'profile': profile, 'expertises': expertises}
	return render(request, 'profile.html', response)

tugas_1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
from fitur_profile.models import Person

# Create your views here.
response = {}
def index(request):
    profile = Person.objects.get(pk=1)
    response['profile'] = profile
    status = Status.objects.all()[::-1]
    response['status'] = status
    html = 'status.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

def delete_status(request):
    status = Status.objects.get(id=int(request.POST.get("id-value", "")))
    status.delete()
    return HttpResponseRedirect('/status/')

fitur_add_friend/templates/friends.html
{% extends "projects.html" %}

{% block content %}
  <h1 style="font-size:320%; color:blue">Friends</h1>
  <hr/>

      <form id="form" method="POST" action="{% url 'friends:add_friend' %}" style="margin-bottom:6rem">
          {% csrf_token %}
          {{ add_friend_form }}
          <br>
          <button type="submit" class="btn btn-default">Add Friend</button>
      </form>


  <div class="flex">
              {% if friend_list %}
                  {% for person in friend_list %}
                      <div class="flex-item">
                        <a href="#"><i class="fa fa-arrow-down fa-2x"></i></a>
                        <div class="friend-list">
                          <div class="to-do-list-image">
                            <img src="https://i1.wp.com/techieswag.com/wp-content/uploads/2016/11/profile-empty..jpg?ssl=1" class="profile" />
                          </div>
                          <div class="to-do-list">
                              <div class="to-do-list-title">
                                  {{person.name}}
                              </div>
                              <div class="to-do-list-description">
                                  <a href="{{person.url}}">{{person.url}}</a>
                              </div>
                              <div class="to-do-list-date-added">
                                  Added {{person.created_date}}
                              </div>
                          </div>
                        </div>
                      </div>
                  {% endfor %}
              {% else %}
              <div class="alert alert-danger text-center">
                  <strong>Oops!</strong> you have no friend.
              </div>
              {% endif %}
          </div>

{% endblock %}

fitur_add_friend/templates/projects.html
<!doctype html>
{% load staticfiles %}

<html lang="en" class="no-js">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href='http://fonts.googleapis.com/css?family=Lora:400,700|Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/friends.css' %}" />
	<script src="{% static 'js/modernizr.js'%}"></script> <!-- Modernizr -->


	<title>Friends</title>
</head>
<body>
	<a href="#cd-nav" class="cd-nav-trigger">
		Menu<span><!-- used to create the menu icon --></span>
	</a> <!-- .cd-nav-trigger -->

	<main>
		<section class="cd-section projects cd-selected">
			<header>
				<div class="cd-title">
					<h2>Friends</h2>

					<a href="/status/">
						<span>
							<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
								<polygon fill="#FFFFFF" points="15,7 4.4,7 8.4,3 7,1.6 0.6,8 0.6,8 0.6,8 7,14.4 8.4,13 4.4,9 15,9 "/>
							</svg>
						</span>
						Back to update status.
					</a>
				</div> <!-- .cd-title -->
			</header>

			<div class="cd-content">
				<p>
	        <div class="container">
	            {% block content %}
	                <!-- content goes here -->
	            {% endblock %}
	        </div>
			</div>
		</section> <!-- .cd-section -->
		Made with love by A7
	</main>

	<nav class="cd-nav-container" id="cd-nav">
		<header>
			<h3>Navigation</h3>
			<a href="#0" class="cd-close-nav">Close</a>
		</header>

		<ul class="cd-nav">
			<li data-menu="index">
				<a href="/status/">
					<span>
						<svg class="nc-icon outline" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="64px" height="64px" viewBox="0 0 64 64"><g transform="translate(0, 0)"> <polyline data-cap="butt" fill="none" stroke="#9e85d0" stroke-width="2" stroke-miterlimit="10" points="10,24.9 10,60 26,60 26,44 38,44 38,60 54,60 54,24.9 " stroke-linejoin="square" stroke-linecap="butt"></polyline> <polyline data-color="color-2" fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" points=" 4,30 32,6 60,30 " stroke-linejoin="square"></polyline> <rect data-color="color-2" x="26" y="24" fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" width="12" height="10" stroke-linejoin="square"></rect> </g></svg>
					</span>

					<em>Update Status</em>
				</a>
			</li>

			<li  class="cd-selected" data-menu="projects">
				<a href="/friends/">
					<span>
						<svg class="nc-icon outline" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="64px" height="64px" viewBox="0 0 64 64"> <g transform="translate(0, 0)"> <polyline data-color="color-2" fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" points=" 22,12 22,4 42,4 42,12 " stroke-linejoin="square"></polyline> <line fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" x1="44" y1="44" x2="20" y2="44" stroke-linejoin="square"></line> <polyline fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" points="12,44 2,44 2,12 62,12 62,44 52,44 " stroke-linejoin="square"></polyline> <polyline fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" points="58,44 58,60 6,60 6,44 " stroke-linejoin="square"></polyline> <rect data-color="color-2" x="22" y="22" fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" width="20" height="10" stroke-linejoin="square"></rect> <rect data-color="color-2" x="12" y="40" fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" width="8" height="8" stroke-linejoin="square"></rect> <rect data-color="color-2" x="44" y="40" fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" width="8" height="8" stroke-linejoin="square"></rect> </g> </svg>
					</span>

					<em>Friends</em>
				</a>
			</li>

			<li data-menu="about">
				<a href="/statistics/">
					<span>
						<svg class="nc-icon outline" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="64px" height="64px" viewBox="0 0 64 64"> <g transform="translate(0, 0)"> <polyline data-color="color-2" fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" points=" 38,16 62,16 62,58 2,58 2,16 26,16 " stroke-linejoin="square"></polyline> <path fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" d="M38,20H26V8 c0-3.3,2.7-6,6-6h0c3.3,0,6,2.7,6,6V20z" stroke-linejoin="square"></path> <path fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" d="M20,38L20,38 c-2.2,0-4-1.8-4-4v-2c0-2.2,1.8-4,4-4h0c2.2,0,4,1.8,4,4v2C24,36.2,22.2,38,20,38z" stroke-linejoin="square"></path> <line fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" x1="38" y1="36" x2="54" y2="36" stroke-linejoin="square"></line> <line fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" x1="38" y1="44" x2="48" y2="44" stroke-linejoin="square"></line> <path fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" d="M30,48H10v0 c0-3.3,2.7-6,6-6h8C27.3,42,30,44.7,30,48L30,48z" stroke-linejoin="square"></path> <line fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" x1="32" y1="12" x2="32" y2="10" stroke-linejoin="square"></line> </g> </svg>
					</span>

					<em>Statistic</em>
				</a>
			</li>
			<li data-menu="careers">
				<a href="/profile/">
					<span>
						<svg class="nc-icon outline" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="64px" height="64px" viewBox="0 0 64 64"> <g transform="translate(0, 0)"> <polyline data-cap="butt" data-color="color-2" fill="none" stroke="#9e85d0" stroke-width="2" stroke-miterlimit="10" points="24,40 28,48 36,48 40,40 " stroke-linejoin="square" stroke-linecap="butt"></polyline> <line data-cap="butt" data-color="color-2" fill="none" stroke="#9e85d0" stroke-width="2" stroke-miterlimit="10" x1="24" y1="62" x2="28" y2="48" stroke-linejoin="square" stroke-linecap="butt"></line> <line data-cap="butt" data-color="color-2" fill="none" stroke="#9e85d0" stroke-width="2" stroke-miterlimit="10" x1="36" y1="48" x2="40" y2="62" stroke-linejoin="square" stroke-linecap="butt"></line> <path data-cap="butt" fill="none" stroke="#9e85d0" stroke-width="2" stroke-miterlimit="10" d="M39.7,40H40c12.2,0,22,9.8,22,22v0H2 v0c0-12.2,9.8-22,22-22h0.3" stroke-linejoin="square" stroke-linecap="butt"></path> <path data-cap="butt" fill="none" stroke="#9e85d0" stroke-width="2" stroke-miterlimit="10" d="M47.9,27.5C47.2,35.7,40.3,42,32,42 h0c-8.3,0-15.2-6.4-15.9-14.5" stroke-linejoin="square" stroke-linecap="butt"></path> <path fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" d="M16,18c0-8.8,7.2-16,16-16 h0c8.8,0,16,7.2,16,16" stroke-linejoin="square"></path> <path data-color="color-2" fill="none" stroke="#9e85d0" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" d="M12.1,18 c0,0.3-0.1,0.7-0.1,1c0,6.1,4.9,11,11,11c3.7,0,7-1.9,9-4.7c2,2.8,5.3,4.7,9,4.7c6.1,0,11-4.9,11-11c0-0.3,0-0.7-0.1-1H12.1z" stroke-linejoin="square"></path> </g> </svg>
					</span>

					<em>Profile</em>
				</a>
			</li>

		</ul> <!-- .cd-3d-nav -->
	</nav>

	<div class="cd-overlay"><!-- shadow layer visible when navigation is visible --></div>

	<script src="{% static 'js/jquery-2.1.1.js'%}"></script>
	<script src="{% static 'js/main.js'%}"></script> <!-- Resource jQuery -->
</body>
</html>

fitur_profile/templates/profile.html
{% extends "projects1.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <style type="text/css">

    .pill{
      height: 10%;
      width: 65%;
      border-radius: 50px;
      text-align: center;
      background-color: #E2E1DC;
    }
  </style>
</head>
<body>
  <div class="dope-yellow" style="margin: 0 0 0 -100;">
    <br>
    <br>

    <div class="row">
      <div class="col-xs-12 col-lg-4 col-lg-offset-1 lato-font">
        <h1>Profile</h1>
        <h2 >{{ profile.first_name }} {{ profile.last_name }}</h2>
        <h3 ><i>{{ profile.email }}</i></h3>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
        <center>
          <div >
            <img class="img-circle img-border" style="width: 90%;" id="grumpy-profile" src= {{ profile.photo }} alt="grumpy profile" width="350px">
          </div>
        </center>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-lg-offset-1">
          <h2>Description:</h2>
          <p>{{ profile.description }}</p>
      </div>
    </div>

    <div class="row lato-font" >
      <div class="col-xs-12 col-lg-4 col-lg-offset-1 lato-font" >
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <h4>
            Birthday:
          </h4>
          <h4>
            {{ profile.birth_date }}
          </h4>
          <br>
          <h4>
            Gender:
          </h4>
          <h4>
            {{ profile.gender }}
          </h4>
        </div>
      </div>
      <div class="col-xs-12 col-lg-7 lato-font">
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-4">
          <h4>Expertises: </h4>
          {% for data in expertises %}
                <div class="pill">
                  <h4 style="padding: 5% 0 0 0;">{{data.expertise}}</h4>             
                </div>
          {% endfor %}
        </div>
      </div> 
    </div>

  </div>
</body>

</html>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>One Page CSS Navigation</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css'>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/tugas_ppw_1.css' %}">
  <style type="text/css">
      iframe {
        width: 100%;
        height: 100%;
      }
      #profile-iframe{
        margin: 0 0 0 150;
      }
  </style>
</head>

<body>
  <div class="ct" id="t1">
 <div class="ct" id="t2">
   <div class="ct" id="t3">
     <div class="ct" id="t4">
<section>
 <ul>
   <a href="#t1"><li class="icon fa fa-home" id="uno"></li></a>
   <a href="#t2"><li class="icon fa fa-keyboard-o" id="dos"></li></a>
   <a href="#t3"><li class="icon fa fa-dashcube" id="tres"></li></a>
   <a href="#t4"><li class="icon fa fa-user-plus" id="cuatro"></li></a>
 </ul>
  <div class="page" id="p1">
    <iframe src="http://localhost:8000/profile/" id="profile-iframe"></iframe>
  </div>
  <div class="page" id="p2">
    <li class="icon fa fa-keyboard-o"><span class="title">Update Status</span></li>
  </div>
  <div class="page" id="p3">
    <li class="icon fa fa-dashcube"><span class="title">Dashboard</span></li>
  </div>
  <div class="page" id="p4">
   <li class="icon fa fa-user-plus"><span class="title">Add Friends</span><span class="hint">Add ur bloody friends here</span></li>
  </div>
    <p class="credit"> Made with love by A-7 Group.</p>
</section>

     </div>
     </div>
   </div>
  </div>


</body>
</html>

tugas_1/templates/status.html
{% extends "index.html" %}

{% block content %}
<style type="text/css">
    .face {
    border-radius: 100%;}

    .circleborder {
    border: 5px solid #ffcbd3;
    border-radius: 100%;
    display: inline-block;
    float: left;
    }

    #status {
        flex-basis: auto;
        flex-grow: 0;
        flex-shrink: 0;
        border: 2px solid grey;
        background-color: white;
        border-radius: 5px;
        width: 78vw;
        padding-top: 20px;
        padding-left: 20px;
        padding-right: 20px;
        padding-bottom: 25px;
        margin-bottom: 10px;
    }
    .status-list-title {
        margin-top: 22px;
        margin-left: 75px;
        font-size: 20px;
        text-align: justify;
    }
    .status-list-description {
        margin-top: 30px;
        margin-left: 10px;
        text-align: justify;
    }
    #grumpy-profile{
        margin: 15px;
        margin-top: -25px;
    }
    #delete-button{
        width: 60px;
        height: 20px;
        padding: 0px;
        margin-left: 70vw;
        background-color: purple;
        border-color: purple    ;
        color:white;
        text-decoration: none;
        font-weight: bolder;
        -webkit-transition-duration: 0.4s; /* Safari */
        transition-duration: 0.4s;
    }

    #delete-button:hover{
        background-color: white;
        color: purple;
        text-decoration: none;
    }
    #date-added {
        margin-top: 50px;
        color: grey;
        text-align: left;
        margin-left: 10px;
    }
    #post {
        width: 80px;
        height: 40px;
        padding: 0px;
        border-radius: 10%;
        margin-top: 10px;
        background-color: #9c7cea;
        border-color: #9c7cea;
        color:white;
        text-decoration: none;
        font-weight: bolder; 
    }
    @media only screen and (max-width: 768px) {
        #input-list .container #form .status-form-textarea{
            width: 90vw;
        }
        #status {
            width: 90vw;
        }

        #delete-button {
            margin-left: 60vw;
        }
</style>
<section id="input-list">
	<div class="container">
		<form id="form" method="POST" action="{% url 'tugas-1:add_status' %}">
			{% csrf_token %}
			{{ status_form }}
            <br>
			<button type="submit" id="post">Post</button>
		</form>
        <br>
	</div>
</section>
<section>
	<div class="container">
		{% for data in status %}
            <div class="flex-item" id="status">
                <div class="status-list">
                    <div class="circleborder">
                        <img class="face" src= {{ profile.photo }} alt="face" width="50" height="50" align="left">
                    </div>
                </div>
                <div class="status-list-title">
                    <b> {{profile.first_name}} {{profile.last_name}} </b>   
                </div>
                 <div class="status-list-description">
                    {{data.description}}
                </div>
                <div id="date-added" class="status-list-date-added">
                    {{data.created_date}}
                </div>
                <div class="to-do-list-delete">
                        <div class="to-do-list-delete-button">
                            <form method="POST" action="{% url 'tugas-1:delete_status' %}">
                                {% csrf_token %}
                                <button id="delete-button" type="submit" value="{{data.id}}" name="id-value">Delete</button>
                            </form>
                        </div>
                    </div>
            </div>
        {% endfor %}
	</div>
</section>
{% endblock %}

tugas_1/templates/tugas_1.html
{% load staticfiles %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>One Page CSS Navigation</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css'>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/tugas_ppw_1.css' %}">
  <style type="text/css">
   /*   iframe {
        width: 100%;
        height: 100%;
      }*/
  </style>
</head>

<body>
  <div class="ct" id="t1">
 <div class="ct" id="t2">
   <div class="ct" id="t3">
     <div class="ct" id="t4">
<section>
 <ul>
   <a href="#t1"><li class="icon fa fa-home" id="uno"></li></a>
   <a href="#t2"><li class="icon fa fa-keyboard-o" id="dos"></li></a>
   <a href="#t3"><li class="icon fa fa-dashcube" id="tres"></li></a>
   <a href="#t4"><li class="icon fa fa-user-plus" id="cuatro"></li></a>
 </ul>
  <div class="page" id="p1" style="margin: 0 0 0 -200;">
    <iframe src="http://localhost:8000/profile/" style="width: 100%;
        height: 100%;">asdasdass</iframe>
  </div>
  <div class="page" id="p2">
    <li class="icon fa fa-keyboard-o"><span class="title">Update Status</span></li>
  </div>
  <div class="page" id="p3">
    <li class="icon fa fa-dashcube"><span class="title">Dashboard</span></li>
  </div>
  <div class="page" id="p4">
   <li class="icon fa fa-user-plus"><span class="title">Add Friends</span><span class="hint">Add ur bloody friends here</span></li>
  </div>
    <p class="credit"> Made with love by A-7 Group.</p>
</section>

     </div>
     </div>
   </div>
  </div>


</body>
</html>